/**
 * Created by yuyu on 2020/2/4.
 */

//用于使chart自适应高度和宽度,通过窗体高宽计算容器高宽
function resizeContainer(chart_id, chart_div, width_ratio = 1, height_ratio = false) {
    let container = document.getElementById(chart_id);
    container.style.width = $("#"+chart_div).width() * width_ratio + 'px';
    if (height_ratio != false){
        // 有长宽比例的时候
        container.style.height = $("#"+chart_id).width() * height_ratio + 'px';
    }
}

function update_overall_table() {
    $.getJSON('./data/data/overall.json')
        .done(function (data) {
            data = data['results'];
            $("#confirmedCount").text(data[0]['confirmedCount']);
            $("#suspectedCount").text(data[0]['suspectedCount']);
            $("#curedCount").text(data[0]['curedCount']);
            $("#deadCount").text(data[0]['deadCount']);
            $("#seriousCount").text(data[0]['seriousCount']);
            data[0]['confirmedIncr'] = data[0]['confirmedIncr'] > 0 ? "+"+data[0]['confirmedIncr'].toString() : data[0]['confirmedIncr'].toString()
            data[0]['suspectedIncr'] = data[0]['suspectedIncr'] > 0 ? "+"+data[0]['suspectedIncr'].toString() : data[0]['suspectedIncr'].toString()
            data[0]['curedIncr'] = data[0]['curedIncr'] > 0 ? "+"+data[0]['curedIncr'].toString() : data[0]['curedIncr'].toString()
            data[0]['deadIncr'] = data[0]['deadIncr'] > 0 ? "+"+data[0]['deadIncr'].toString() : data[0]['deadIncr'].toString()
            data[0]['seriousIncr'] = data[0]['seriousIncr'] > 0 ? "+"+data[0]['seriousIncr'].toString() : data[0]['seriousIncr'].toString()
            $("#confirmedIncr").html('较昨日'+ "<span class='text-danger'>"+data[0]['confirmedIncr']+"</span>");
            $("#suspectedIncr").html('较昨日'+ "<span class='text-warning'>"+data[0]['suspectedIncr']+"</span>");
            $("#curedIncr").html('较昨日'+ "<span class='text-success'>"+data[0]['curedIncr']+"</span>");
            $("#deadIncr").html('较昨日'+ "<span class='text-primary'>"+data[0]['deadIncr']+"</span>");
            $("#seriousIncr").html('较昨日'+ "<span class='text-info'>"+data[0]['seriousIncr']+"</span>");
        })
        .fail(function () {
            console.log('更新数据预览表失败')
        })
}

function update_overall_table_en() {
    $.getJSON('./data/data/overall_en.json')
        .done(function (data) {
            data = data['results']; // UNDO 2021-10-11
            $("#confirmedCount").text(data[0]['confirmedCount']);
            $("#activeCount").text(data[0]['confirmedCount']-data[0]['curedCount']-data[0]['deadCount']);
            $("#curedCount").text(data[0]['curedCount']);
            $("#deadCount").text(data[0]['deadCount']);
            data[0]['confirmedIncr'] = data[0]['confirmedIncr'] > 0 ? "+"+data[0]['confirmedIncr'].toString() : data[0]['confirmedIncr']
            data[0]['curedIncr'] = data[0]['curedIncr'] > 0 ? "+"+data[0]['curedIncr'].toString() : data[0]['curedIncr']
            data[0]['deadIncr'] = data[0]['deadIncr'] > 0 ? "+"+data[0]['deadIncr'].toString() : data[0]['deadIncr']
            let activeIncr = data[0]['confirmedIncr'] - data[0]['curedIncr'] - data[0]['deadIncr'];
            activeIncr = activeIncr > 0 ? "+"+ activeIncr.toString() : activeIncr;
            $("#confirmedIncr").html('Today'+ "<span class='text-info'>"+data[0]['confirmedIncr']+"</span>");
            $("#curedIncr").html('Today'+ "<span class='text-success'>"+data[0]['curedIncr']+"</span>");
            $("#deadIncr").html('Today'+ "<span class='text-primary'>"+data[0]['deadIncr']+"</span>");
            $("#activeIncr").html('Today'+ "<span class='text-danger'>"+activeIncr+"</span>");
        })
        .fail(function () {
            console.log('更新数据预览表失败')
        });
}


//手机端自适应
remChange();
window.addEventListener('resize', remChange);
function remChange() {
    remove();
    let width = window.screen.width;
    let fixedw = 760;
    let scale = width / fixedw; //获取到的屏幕宽度比上自定义的760宽度 获得对应比例
    let meta = document.createElement("meta");
    meta.setAttribute('name', 'viewport');
    //将对应比例填入meta标签即可实现宽度自适应
    meta.setAttribute('content', `width=device-width, initial-scale=${scale}`); //maximum-scale=${scale}, minimum-scale=${scale}, user-scalable=no
    //meta将标签添加到文档中即可
    document.head.appendChild(meta);
}
function remove() {
    let meta = document.querySelector("meta[name='viewport']");
    if (meta != null) {
        document.head.removeChild(meta);
    }
}


$(function () {
    if ($(window).width() < 768) {
        $("#myNav").css("marginTop", $('#defaultNav').height()+5);
        $('#myNav').show()
    }else{
        $('#myNav').hide()
    }
});


var abbr = {
'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA', 'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK', 'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY', 'District of Columbia': 'D.C.', 'Unassigned Location (From Diamond Princess)': 'Unassigned Location (From Diamond Princess)', 'Grand Princess Cruise Ship': 'Grand Princess Cruise Ship', 'Alberta': 'Alberta', 'British Columbia': 'British Columbia', 'Manitoba': 'MB', 'New Brunswick': 'NB', 'Newfoundland and Labrador': 'NL', 'Nova Scotia': 'NS', 'Northwest Territories': 'NT', 'Nunavut': 'NU', 'Ontario': 'ON', 'Prince Edward Island': 'PE', 'Quebec': 'QC', 'Saskatchewan': 'SK', 'Yukon': 'YT',
'Andorra': 'AD',
    'United Arab Emirates': 'AE',
    'Afghanistan': 'AF',
    'Antigua and Barbuda': 'AG',
    'Anguilla': 'AI',
    'Albania': 'AL',
    'Armenia': 'AM',
    'Angola': 'AO',
    'Argentina': 'AR',
    'Austria': 'AT',
    'Australia': 'AU',
    'Bhutan': 'BT',
    'Dominica': 'DM',
    'Azerbaijan': 'AZ',
    'Barbados': 'BB',
    'Bangladesh': 'BD',
    'Belgium': 'BE',
    'Burkina-faso': 'BF',
    'Bulgaria': 'BG',
    'Bahrain': 'BH',
    'Burundi': 'BI',
    'Benin': 'BJ',
    'Palestine': 'BL',
    'Bermuda Is.': 'BM',
    'Brunei': 'BN',
    'Bolivia': 'BO',
    'Brazil': 'BR',
    'Bahamas': 'BS',
    'Botswana': 'BW',
    'Belarus': 'BY',
    'Belize': 'BZ',
    'Canada': 'CA',
    'Central African Republic': 'CF',
    'Congo': 'CG',
    'Switzerland': 'CH',
    'Cook Is.': 'CK',
    'Chile': 'CL',
    'Cameroon': 'CM',
    'China': 'CN',
    'Colombia': 'CO',
    'Costa Rica': 'CR',
    'Czech': 'CS',
    'Cuba': 'CU',
    'Cyprus': 'CY',
    'Czech Republic': 'CZ',
    'Germany': 'DE',
    'Djibouti': 'DJ',
    'Denmark': 'DK',
    'Dominica Rep.': 'DO',
    'Algeria': 'DZ',
    'Ecuador': 'EC',
    'Estonia': 'EE',
    'Egypt': 'EG',
    'Spain': 'ES',
    'Ethiopia': 'ET',
    'Finland': 'FI',
    'Fiji': 'FJ',
    'France': 'FR',
    'Gabon': 'GA',
    'United Kingdom': 'UK',
    'Grenada': 'GD',
    'Georgia': 'GE',
    'French Guiana': 'GF',
    'Ghana': 'GH',
    'Gibraltar': 'GI',
    'Gambia': 'GM',
    'Guinea': 'GN',
    'Greece': 'GR',
    'Guatemala': 'GT',
    'Guam': 'GU',
    'Guyana': 'GY',
    'Hongkong': 'HK',
    'Honduras': 'HN',
    'Haiti': 'HT',
    'Hungary': 'HU',
    'Indonesia': 'ID',
    'Ireland': 'IE',
    'Israel': 'IL',
    'India': 'IN',
    'Iraq': 'IQ',
    'Iran': 'IR',
    'Iceland': 'IS',
    'Italy': 'IT',
    'Jamaica': 'JM',
    'Jordan': 'JO',
    'Japan': 'JP',
    'Kenya': 'KE',
    'Kyrgyzstan': 'KG',
    'Cambodia': 'KH',
    'North Korea': 'KP',
    'Korea': 'KR',
    'Republic of Ivory Coast': 'KT',
    'Kuwait': 'KW',
    'Kazakstan': 'KZ',
    'Laos': 'LA',
    'Lebanon': 'LB',
    'St.Lucia': 'LC',
    'Liechtenstein': 'LI',
    'Sri Lanka': 'LK',
    'Liberia': 'LR',
    'Lesotho': 'LS',
    'Lithuania': 'LT',
    'Luxembourg': 'LU',
    'Latvia': 'LV',
    'Libya': 'LY',
    'Morocco': 'MA',
    'Monaco': 'MC',
    'Moldova Republic of': 'MD',
    'Madagascar': 'MG',
    'Mali': 'ML',
    'Burma': 'MM',
    'Mongolia': 'MN',
    'Macao': 'MO',
    'Croatia': 'HR',
    'Montserrat Is': 'MS',
    'Malta': 'MT',
    'Mauritius': 'MU',
    'Maldives': 'MV',
    'Malawi': 'MW',
    'Mexico': 'MX',
    'Malaysia': 'MY',
    'Mozambique': 'MZ',
    'Niger': 'NE',
    'Nigeria': 'NG',
    'Nicaragua': 'NI',
    'Netherlands': 'NL',
    'Norway': 'NO',
    'Nepal': 'NP',
    'Nauru': 'NR',
    'New Zealand': 'NZ',
    'Oman': 'OM',
    'Panama': 'PA',
    'Peru': 'PE',
    'French Polynesia': 'PF',
    'Papua New Cuinea': 'PG',
    'Philippines': 'PH',
    'Pakistan': 'PK',
    'Poland': 'PL',
    'Puerto Rico': 'PR',
    'Portugal': 'PT',
    'Paraguay': 'PY',
    'Qatar': 'QA',
    'Romania': 'RO',
    'Russia': 'RU',
    'Saudi Arabia': 'SA',
    'Solomon Is': 'SB',
    'Seychelles': 'SC',
    'Sudan': 'SD',
    'Sweden': 'SE',
    'Singapore': 'SG',
    'Slovenia': 'SI',
    'Slovakia': 'SK',
    'Sierra Leone': 'SL',
    'San Marino': 'SM',
    'Senegal': 'SN',
    'Somali': 'SO',
    'Suriname': 'SR',
    'Sao Tome and Principe': 'ST',
    'EI Salvador': 'SV',
    'Syria': 'SY',
    'Swaziland': 'SZ',
    'Chad': 'TD',
    'Togo': 'TG',
    'Thailand': 'TH',
    'Tajikstan': 'TJ',
    'Turkmenistan': 'TM',
    'Tunisia': 'TN',
    'Tonga': 'TO',
    'Turkey': 'TR',
    'Trinidad and Tobago': 'TT',
    'Taiwan': 'TW',
    'Tanzania': 'TZ',
    'Ukraine': 'UA',
    'Uganda': 'UG',
    'United States': 'US',
    'Uruguay': 'UY',
    'Uzbekistan': 'UZ',
    'Saint Vincent': 'VC',
    'Venezuela': 'VE',
    'Vietnam': 'VN',
    'Yemen': 'YE',
    'Yugoslavia': 'YU',
    'South Africa': 'ZA',
    'Zambia': 'ZM',
    'Zaire': 'ZR',
    'Zimbabwe': 'ZW'};

var translation_dictionary = {
    '确诊': 'Confirmed',
    '治愈': 'Recovered',
    '死亡': 'Death',
    'Qatar': '卡塔尔',
    '现存确诊': 'Current Confirmed',
    '疑似': 'Suspected',
    'World': 'World',
    'world': 'World',
    'China': 'China',
    'china': 'China',
    '中国': 'China',
    'Macau': '澳门',
    '世界': 'World',
    'Hong Kong': '香港',
    '男': 'Male',
    '女': 'Female',
    '钻石公主号邮轮': 'Diamond Princess',
    '治愈率': 'Cure Rate',
    '死亡率': 'Death Rate',
    '阿富汗': 'Afghanistan',
    '阿尔巴尼亚': 'Albania',
    '阿尔及利亚': 'Algeria',
    '安道尔': 'Andorra',
    '安哥拉': 'Angola',
    '南极洲': 'Antarctica',
    '安提瓜和巴布达': 'Antigua and Barbuda',
    '阿根廷': 'Argentina',
    '亚美尼亚': 'Armenia',
    '澳大利亚': 'Australia',
    '奥地利': 'Austria',
    '阿塞拜疆': 'Azerbaijan',
    '巴哈马': 'The Bahamas',
    '巴林': 'Bahrain',
    '孟加拉国': 'Bangladesh',
    '巴巴多斯': 'Barbados',
    '白俄罗斯': 'Belarus',
    '比利时': 'Belgium',
    '伯利兹': 'Belize',
    '贝宁': 'Benin',
    '百慕大': 'Bermuda',
    '不丹': 'Bhutan',
    '玻利维亚': 'Bolivia',
    '波斯尼亚和黑塞哥维那': 'Bosnia and Herzegovina',
    '博茨瓦纳': 'Botswana',
    '巴西': 'Brazil',
    '文莱': 'Brunei',
    '保加利亚': 'Bulgaria',
    '布基纳法索': 'Burkina Faso',
    '布隆迪': 'Burundi',
    '柬埔寨': 'Cambodia',
    '喀麦隆': 'Cameroon',
    '加拿大': 'Canada',
    '佛得角': 'Cape Verde',
    '中非共和国': 'Central African Republic',
    '乍得': 'Chad',
    '智利': 'Chile',
    '哥伦比亚': 'Colombia',
    '科摩罗': 'Comoros',
    '刚果共和国': 'Republic of the Congo',
    '哥斯达黎加': 'Costa Rica',
    '克罗地亚': 'Croatia',
    '古巴': 'Cuba',
    '塞浦路斯': 'Cyprus',
    '捷克共和国': 'Czech Republic',
    '丹麦': 'Denmark',
    '吉布提': 'Djibouti',
    '多米尼加': 'Dominica',
    '多明尼加共和国': 'Dominican Republic',
    '厄瓜多尔': 'Ecuador',
    '埃及': 'Egypt',
    '萨尔瓦多': 'El Salvador',
    '赤道几内亚': 'Equatorial Guinea',
    '厄立特里亚': 'Eritrea',
    '爱沙尼亚': 'Estonia',
    '埃塞俄比亚': 'Ethiopia',
    '福克兰群岛': 'Falkland Islands',
    '法罗群岛': 'Faroe Islands',
    '斐济': 'Fiji',
    '芬兰': 'Finland',
    '法国': 'France',
    '法属圭亚那': 'French Guiana',
    '法属南半球和南极领地': 'French Southern and Antarctic Lands',
    '加蓬': 'Gabon',
    '冈比亚': 'Gambia',
    '加沙': 'Gaza Strip',
    '格鲁吉亚': 'Georgia',
    '德国': 'Germany',
    '加纳': 'Ghana',
    '希腊': 'Greece',
    '格陵兰': 'Greenland',
    '格林纳达': 'Grenada',
    '瓜德罗普': 'Guadeloupe',
    '危地马拉': 'Guatemala',
    '几内亚': 'Guinea',
    '几内亚比绍': 'Guinea Bissau',
    '圭亚那': 'Guyana',
    '海地': 'Haiti',
    '洪都拉斯': 'Honduras',
    '香港': 'Hong Kong',
    '匈牙利': 'Hungary',
    '冰岛': 'Iceland',
    '印度': 'India',
    '印尼': 'Indonesia',
    '伊朗': 'Iran',
    '伊拉克': 'Iraq',
    '伊拉克阿拉伯中立区': 'Iraq-Saudi Arabia Neutral Zone',
    '爱尔兰': 'Ireland',
    '马恩岛': 'Isle of Man',
    '以色列': 'Israel',
    '意大利': 'Italy',
    '科特迪瓦': 'Ivory Coast',
    '牙买加': 'Jamaica',
    '扬马延岛': 'Jan Mayen',
    '日本': 'Japan',
    '约旦': 'Jordan',
    '哈萨克斯坦': 'Kazakhstan',
    '肯尼亚': 'Kenya',
    '凯尔盖朗群岛': 'Kerguelen',
    '基里巴斯': 'Kiribati',
    '北朝鲜': 'North Korea',
    '韩国': 'Korea',
    '科威特': 'Kuwait',
    '吉尔吉斯斯坦': 'Kyrgyzstan',
    '老挝': 'Laos',
    '拉脱维亚': 'Latvia',
    '黎巴嫩': 'Lebanon',
    '莱索托': 'Lesotho',
    '利比里亚': 'Liberia',
    '利比亚': 'Libya',
    '列支敦士登': 'Liechtenstein',
    '立陶宛': 'Lithuania',
    '卢森堡': 'Luxembourg',
    '澳门': 'Macau',
    '马其顿': 'Macedonia',
    '马达加斯加': 'Madagascar',
    '马拉维': 'Malawi',
    '马来西亚': 'Malaysia',
    '马尔代夫': 'Maldives',
    '马里': 'Mali',
    '马耳他': 'Malta',
    '马提尼克': 'Martinique',
    '毛里塔尼亚': 'Mauritania',
    '毛里求斯': 'Mauritius',
    '墨西哥': 'Mexico',
    '摩尔多瓦': 'Moldova',
    '摩纳哥': 'Monaco',
    '蒙古': 'Mongolia',
    '摩洛哥': 'Morocco',
    '莫桑比克': 'Mozambique',
    '缅甸': 'Myanmar',
    '纳米比亚': 'Namibia',
    '尼泊尔': 'Nepal',
    '荷兰': 'Netherlands',
    '新喀里多尼亚': 'New Caledonia',
    '新西兰': 'New Zealand',
    '尼加拉瓜': 'Nicaragua',
    '尼日尔': 'Niger',
    '尼日利亚': 'Nigeria',
    '北马里亚纳群岛': 'Northern Mariana Islands',
    '挪威': 'Norway',
    '阿曼': 'Oman',
    '巴基斯坦': 'Pakistan',
    '巴拿马': 'Panama',
    '巴布亚新几内亚': 'Papua New Guinea',
    '巴拉圭': 'Paraguay',
    '秘鲁': 'Peru',
    '菲律宾': 'Philippines',
    '波兰': 'Poland',
    '葡萄牙': 'Portugal',
    '波多黎各': 'Puerto Rico',
    '卡塔尔': 'Qatar',
    '留尼旺岛': 'Reunion',
    '罗马尼亚': 'Romania',
    '俄罗斯': 'Russia',
    '卢旺达': 'Rwanda',
    '圣马力诺': 'San Marino',
    '圣多美和普林西比': 'Sao Tome and Principe',
    '沙特阿拉伯': 'Saudi Arabia',
    '塞内加尔': 'Senegal',
    '塞舌尔': 'Seychelles',
    '塞拉利昂': 'Sierra Leone',
    '新加坡': 'Singapore',
    '斯洛伐克': 'Slovakia',
    '斯洛文尼亚': 'Slovenia',
    '所罗门群岛': 'Solomon Islands',
    '索马里': 'Somalia',
    '南非': 'South Africa',
    '西班牙': 'Spain',
    '斯里兰卡': 'Sri Lanka',
    '圣': 'St. Christopher-Nevis',
    '圣露西亚': 'St. Lucia',
    '圣文森特和格林纳丁斯': 'St. Vincent and the Grenadines',
    '苏丹': 'Sudan',
    '苏里南': 'Suriname',
    '斯瓦尔巴特群岛': 'Svalbard',
    '斯威士兰': 'Swaziland',
    '瑞典': 'Sweden',
    '瑞士': 'Switzerland',
    '叙利亚': 'Syria',
    '台湾': 'Taiwan',
    '塔吉克斯坦': 'Tajikistan',
    '坦桑尼亚': 'United Republic of Tanzania',
    '泰国': 'Thailand',
    '多哥': 'Togo',
    '汤加': 'Tonga',
    '特里尼达和多巴哥': 'Trinidad and Tobago',
    '突尼斯': 'Tunisia',
    '土耳其': 'Turkey',
    '土库曼斯坦': 'Turkmenistan',
    '特克斯和凯科斯群岛': 'Turks and Caicos Islands',
    '乌干达': 'Uganda',
    '乌克兰': 'Ukraine',
    '阿联酋': 'United Arab Emirates',
    '英国': 'United Kingdom',
    '美国': 'United States',
    '乌拉圭': 'Uruguay',
    '乌兹别克斯坦': 'Uzbekistan',
    '瓦努阿图': 'Vanuatu',
    '委内瑞拉': 'Venezuela',
    '越南': 'Vietnam',
    '西撒哈拉': 'Western Sahara',
    '西萨摩亚': 'Western Samoa',
    '也门': 'Yemen',
    '南斯拉夫': 'Yugoslavia',
    '刚果民主共和国': 'Democratic Republic of the Congo',
    '赞比亚': 'Zambia',
    '津巴布韦': 'Zimbabwe',
    '南苏丹': 'South Sudan',
    '索马里兰': 'Somaliland',
    '黑山': 'Montenegro',
    '科索沃': 'Kosovo',
    '塞尔维亚': 'Republic of Serbia',
    '武汉': 'Wuhan',
    '孝感': 'Xiaogan',
    '黄冈': 'Huanggang',
    '荆州': 'Jingzhou',
    '随州': 'Suizhou',
    '襄阳': 'Xiangyang',
    '鄂州': 'Ezhou',
    '黄石': 'Huangshi',
    '宜昌': 'Yichang',
    '荆门': 'Jingmen',
    '咸宁': 'Xianning',
    '十堰': 'Shiyan',
    '仙桃': 'peach of immortality',
    '天门': 'Tianmen',
    '恩施州': 'enshi',
    '潜江': 'Qianjiang',
    '神农架林区': 'Shennongjia Forestry District ',
    '昆明': 'Kunming',
    '昭通': 'Zhaotong',
    '西双版纳': 'Xishuangbanna',
    '曲靖': 'Qujing',
    '玉溪': 'Yuxi',
    '大理州': 'Dali Prefecture',
    '保山': 'Baoshan',
    '红河州': 'Honghe Prefecture',
    '丽江': 'Lijiang',
    '普洱': "Pu'er Tea",
    '德宏州': 'Dehong',
    '楚雄州': 'Chuxiong',
    '文山州': 'Wenshan Prefecture',
    '临沧': 'Lincang',
    '西安': "Xi'an",
    '汉中': 'Hanzhoung',
    '安康': 'Ankang',
    '渭南': 'Weinan',
    '咸阳': 'Xianyang',
    '宝鸡': 'Baoji',
    '商洛': 'Shangluo',
    '铜川': 'Tongchuan',
    '延安': "Yan'an",
    '榆林': 'Yulin',
    '韩城': 'Hancheng',
    '杨凌': 'Yangling',
    '待明确地区': 'Areas to be defined',
    '信阳': 'Xinyang',
    '南阳': 'Nanyang',
    '驻马店': 'Zhumadian',
    '郑州': 'Zhengzhou',
    '商丘': 'Shangqiu',
    '周口': 'Zhoukou',
    '新乡': 'Xinxiang',
    '平顶山': 'Pingdingshan',
    '安阳': 'Anyang',
    '许昌': 'Xuchang',
    '漯河': 'Luohe',
    '洛阳': 'Luoyang',
    '焦作': 'Jiaozuo',
    '开封': 'Kaifeng',
    '鹤壁': 'Hebi',
    '濮阳': 'Puyang',
    '三门峡': 'Sanmenxia',
    '济源': 'Jiyuan',
    '苏州': 'Suzhou',
    '南京': 'Nanjing',
    '徐州': 'Xuzhou',
    '淮安': 'Huaian',
    '无锡': 'Wuxi',
    '连云港': 'Lianyungang',
    '常州': 'Changzhou',
    '南通': 'Nantong',
    '泰州': 'Taizhou',
    '盐城': 'ynz',
    '扬州': 'Yangzhou',
    '镇江': 'Zhenjiang',
    '宿迁': 'Suqian',
    '唐山': 'Tangshan',
    '沧州': 'Cangzhou',
    '张家口': 'Zhangjiakou',
    '邯郸': 'Handan',
    '石家庄': 'Shijiazhuang',
    '保定': 'Baoding',
    '廊坊': 'Langfang',
    '邢台': 'Xingtai',
    '秦皇岛': 'Qinghuangdao',
    '承德': 'Chengde',
    '衡水': 'Hengshui',
    '沈阳': 'Shenyang',
    '大连': 'Dalian',
    '锦州': 'Jinzhou',
    '盘锦': 'Panjin',
    '葫芦岛': 'Huludao',
    '阜新': 'Fuxin',
    '铁岭': 'Tieling',
    '朝阳': 'Chaoyang',
    '丹东': 'Dandong',
    '鞍山': 'Anshan',
    '本溪': 'Benxi',
    '辽阳': 'Liaoyang',
    '营口': 'Yingkou',
    '深圳': 'Shenzhen',
    '广州': 'Guangzhou',
    '东莞': 'Dongguan',
    '珠海': 'Zhuhai',
    '佛山': 'Foshan',
    '中山': 'Zhongshan',
    '惠州': 'Huizhou',
    '江门': 'Jiangmen',
    '汕头': 'Shantou',
    '湛江': 'Zhanjiang',
    '茂名': 'Maoming',
    '肇庆': 'Zhaoqing',
    '阳江': 'Yangjiang',
    '梅州': 'Meizhou',
    '清远': 'Qingyuan',
    '韶关': 'Shaoguan',
    '揭阳': 'Jieyang',
    '潮州': 'Chaozhou',
    '汕尾': 'Shanwei',
    '河源': 'Heyuan',
    '包头': 'Baotou',
    '鄂尔多斯': 'Erdos',
    '呼和浩特': 'Hohhot',
    '通辽': 'Tongliao',
    '巴彦淖尔': 'Bayannaoer',
    '呼伦贝尔': 'Hulun Buir',
    '赤峰': 'Chifeng',
    '锡林郭勒盟': 'Xilingol League',
    '乌兰察布': 'Wulanchabu',
    '乌海市': 'Wuhai City',
    '兴安盟': 'Xingan Meng',
    '贵阳': 'Guiyang',
    '遵义': 'Zunyi',
    '毕节': 'Bijie',
    '黔南州': 'Qiannan',
    '黔东南州': 'Qiandongnan Prefecture',
    '六盘水': 'Liupanshui',
    '铜仁': 'Tongren',
    '安顺': 'Anshun',
    '黔西南州': 'Qianxi',
    '银川': 'Yinchuan',
    '吴忠': 'Wu Zhong',
    '固原': 'Guyuan',
    '中卫': 'Central defender',
    '宁东': 'Ningdong',
    '石嘴山': 'Shizuishan',
    '蚌埠': 'Bengbu',
    '合肥': 'Hefei',
    '阜阳': 'Fuyang',
    '亳州': 'Bozhou',
    '六安': "Lu'an",
    '安庆': 'Anqing',
    '宿州': 'Suzhou',
    '马鞍山': "Ma'anshan",
    '芜湖': 'Wuhu',
    '淮北': 'Huaibei',
    '铜陵': 'Tongling',
    '淮南': 'Huainan',
    '池州': 'Chizhou',
    '滁州': 'Chuzhou',
    '黄山': 'Mount Huangshan',
    '宣城': 'Xuancheng',
    '长沙': 'Changsha',
    '岳阳': 'Yueyang',
    '邵阳': 'Shaoyang',
    '株洲': 'Zhuzhou',
    '常德': 'Changde',
    '娄底': 'Loudi',
    '益阳': 'Yiyang',
    '郴州': 'Chenzhou',
    '湘潭': 'Xiangtan',
    '衡阳': 'city in Hunan',
    '永州': 'Yongzhou',
    '怀化': 'Huaihua',
    '湘西自治州': 'Xiangxi Autonomous Prefecture',
    '张家界': 'Zhangjiajie',
    '温州': 'Wenzhou',
    '宁波': 'Ningbo',
    '杭州': 'Hangzhou',
    '台州': 'Taizhou',
    '嘉兴': 'Jiaxing',
    '金华': 'Jinhua',
    '绍兴': 'Shaoxing',
    '衢州': 'Quzhou',
    '丽水': 'Lishui',
    '湖州': 'Huzhou',
    '舟山': 'Zhoushan',
    '南昌': 'Nanchang',
    '上饶': 'Shangrao',
    '九江': 'Jiujiang',
    '新余': 'Xinyu',
    '宜春': 'Yichun',
    '赣州': 'Ganzhou',
    '抚州': 'Fuzhou',
    '萍乡': 'Pingxiang',
    '鹰潭': 'Yingtan',
    '吉安': "Ji'an",
    '景德镇': 'Jingdezhen',
    '赣江新区': 'Ganjiang New Area',
    '乌鲁木齐': 'Urumqi',
    '伊犁州': 'Yili Prefecture',
    '兵团第四师': 'The fourth division of the Corps',
    '兵团第九师': 'The ninth division of the Corps',
    '昌吉州': 'changji',
    '巴州': 'Bazhou',
    '兵团第八师石河子市': 'Shihezi City, the eighth division of the Corps',
    '兵团第六师五家渠市': 'Wujiaqu City, the sixth division of the Corps',
    '兵团第十二师': 'The 12th division of the Corps',
    '吐鲁番市': 'Turpan City',
    '兵团第七师': '7th Division of corps',
    '阿克苏地区': 'Aksu Region',
    '三亚': 'Sanya',
    '海口': 'Haikou',
    '儋州': 'Danzhou',
    '万宁': 'Wanning',
    '昌江': 'Changjiang',
    '澄迈': 'Chengmai',
    '琼海': 'Qionghai',
    '临高': 'ascend a height',
    '陵水': 'Lingshui',
    '保亭': 'Baoting',
    '东方': 'east',
    '文昌': 'God of Literature',
    '乐东': 'Ledong',
    '定安': 'Ding An',
    '琼中': 'Qiong Zhong',
    '成都': 'Chengdu',
    '甘孜州': 'The state of Gansu',
    '达州': 'Dazhou',
    '南充': 'Nao',
    '广安': "Guang'an",
    '巴中': 'Bazhong',
    '内江': 'Neijiang',
    '绵阳': 'Mianyang',
    '泸州': 'Luzhou',
    '德阳': 'Deyang',
    '宜宾': 'Yibin',
    '凉山州': 'Liangshan Prefecture',
    '自贡': 'Zigong',
    '遂宁': 'Suining',
    '眉山': 'Meishan',
    '雅安': "Ya'an",
    '广元': 'Guangyuan',
    '攀枝花': 'Panzhihua',
    '乐山': 'Leshan',
    '资阳': 'Ziyang',
    '阿坝州': 'Aba Prefecture',
    '福州': 'Fuzhou',
    '莆田': 'Putian',
    '泉州': 'Quanzhou',
    '厦门': 'Xiamen',
    '宁德': 'Ningde',
    '南平': 'Nanping',
    '漳州': 'Zhangzhou',
    '三明': 'Sanming',
    '龙岩': 'Longyan',
    '青岛': 'Qingdao',
    '济南': "Ji'nan",
    '烟台': 'Yantai',
    '潍坊': 'Weifang',
    '聊城': 'Liaocheng',
    '临沂': 'Linyi',
    '济宁': 'Jining',
    '威海': 'Weihai',
    '德州': 'Texas',
    '泰安': "Tai'an",
    '淄博': 'Zibo',
    '枣庄': 'Zaozhuang',
    '日照': 'sunshine',
    '菏泽': 'Heze',
    '滨州': 'Binzhou',
    '长春': 'Changchun',
    '四平市': 'Siping City',
    '辽源': 'Liaoyuan',
    '公主岭': 'Gongzhuling',
    '延边': 'Yanbian',
    '通化': 'make well-connected',
    '吉林市': 'Jilin City',
    '松原': 'Songyuan',
    '白城': 'Baicheng',
    '梅河口': 'Meihekou',
    '哈尔滨': 'Harbin',
    '双鸭山': 'Shuangyashan',
    '鸡西': 'Jixi',
    '绥化': 'Suihua',
    '齐齐哈尔': 'Qiqihar',
    '大庆': 'Daqing',
    '七台河': 'Qitaihe',
    '黑河': 'Heihe',
    '牡丹江': 'Mudanjiang',
    '佳木斯': 'Jiamusi',
    '鹤岗': 'Hegang',
    '大兴安岭': 'Greater Khingan Range',
    '南宁': 'Nanning',
    '北海': 'The North Sea',
    '桂林': 'Guilin',
    '河池': 'Hechi',
    '防城港': 'Port of Fangcheng',
    '柳州': 'city in Guangxi',
    '来宾': 'Guest',
    '玉林': 'Yulin',
    '钦州': 'Qinzhou',
    '贵港': 'Guigang',
    '贺州': 'Hezhou',
    '百色': 'Baise',
    '梧州': 'Wuzhou',
    '外地来沪人员': 'Foreign visitors to Shanghai',
    '浦东新区': 'Pudong New Area',
    '宝山区': 'Baoshan District',
    '徐汇区': 'Xuhui District',
    '闵行区': 'Minhang District',
    '静安区': 'Jingan District',
    '松江区': 'Songjiang District',
    '普陀区': 'Putuo District',
    '长宁区': 'Changning District',
    '杨浦区': 'Yangpu District',
    '嘉定区': 'Jiading District',
    '奉贤区': 'Fengxian District',
    '虹口区': 'Hongkou District',
    '黄浦区': 'Huangpu District',
    '青浦区': 'Qingpu District',
    '崇明区': 'Chongming District',
    '金山区': 'Jinshan District',
    '宝坻区': 'Baodi District',
    '河东区': 'Hedong District',
    '河北区': 'Hebei District',
    '北辰区': 'Beichen District',
    '南开区': 'Nankai District',
    '和平区': 'Heping District',
    '外地来津人员': 'Personnel from other places coming to Tianjin',
    '宁河区': 'Ninghe District',
    '东丽区': 'Dongli District',
    '河西区': 'Hexi District',
    '滨海新区': 'Binhai New Area',
    '西青区': 'Xiqing District',
    '红桥区': 'Hongqiao District',
    '津南区': 'Jinnan District',
    '武清区': 'Wuqing District',
    '万州区': 'Wanzhou District',
    '江北区': 'Jiangbei District',
    '綦江区': 'Qijiang District',
    '合川区': 'Hechuan District',
    '垫江县': 'Dianjiang County',
    '奉节县': 'Fengjie County',
    '渝中区': 'Yuzhong District',
    '九龙坡区': 'jiulongpo district',
    '潼南区': 'Tongnan District',
    '南岸区': "Nan'an District",
    '两江新区': 'Liangjiang New Area',
    '大足区': 'Dazu District',
    '忠县': 'Zhongxian',
    '渝北区': 'Yubei District',
    '石柱县': 'Shizhu County',
    '云阳县': 'Yunyang County',
    '长寿区': 'Longevity district',
    '丰都县': 'Fengdu County',
    '荣昌区': 'Rongchang District',
    '沙坪坝区': 'shapingba district',
    '开州区': 'Kai Zhou District',
    '铜梁区': 'Tongliang District',
    '巫溪县': 'Wuxi County',
    '巫山县': 'Wushan County',
    '璧山区': 'Bishan District',
    '巴南区': 'Banan District',
    '永川区': 'Yongchuan District',
    '大渡口区': 'dadukou district',
    '江津区': 'Jiangjin District',
    '高新区': 'High-tech Zone',
    '梁平区': 'Liangping District',
    '涪陵区': 'Fuling District',
    '彭水县': 'Pengshui County',
    '武隆区': 'Wulong District',
    '酉阳县': 'Youyang County',
    '万盛经开区': 'Wansheng Economic Development Zone',
    '城口县': 'Chengkou County',
    '黔江区': 'Qianjiang District',
    '秀山县': 'Xiushan County',
    '晋中': 'Jinzhong',
    '太原': 'Taiyuan',
    '运城': 'Yuncheng',
    '大同': 'Da Tong',
    '长治': 'CiH',
    '忻州': 'Xinzhou',
    '晋城': 'Jincheng',
    '朔州': 'Shuozhou',
    '阳泉': 'Yangquan',
    '吕梁': 'Lvliang',
    '临汾': 'Linfen',
    '兰州': 'Lanzhou',
    '平凉': 'Pingliang',
    '甘南': 'Gannan',
    '天水': 'Tianshui',
    '定西': 'Dingxi',
    '白银': 'silver',
    '陇南': 'Longnan',
    '庆阳': 'Qingyang',
    '临夏': 'Linxia',
    '张掖': 'Zhangye',
    '金昌': 'Jinchang',
    '朝阳区': 'Chaoyang District',
    '平谷区': 'Pinggu District',
    '海淀区': 'Haidian District',
    '西城区': 'Xicheng District',
    '大兴区': 'Daxing District',
    '丰台区': 'Fengtai District',
    '外地来京人员': 'Foreign visitors to Beijing',
    '昌平区': 'Changping District',
    '通州区': 'Tongzhou District',
    '房山区': 'Fangshan District',
    '石景山区': 'Shijingshan District',
    '东城区': 'Dongcheng District',
    '顺义区': 'Shunyi District',
    '怀柔区': 'Huairou District',
    '密云区': 'Miyun District',
    '门头沟区': 'Mentougou District',
    '延庆区': 'Yanqing District',
    '西宁': 'Xining',
    '海北州': 'Haibei Prefecture',
    '拉萨': 'Lhasa',
    '湖北': 'Hubei',
    '云南': 'Yunnan',
    '陕西': 'Shaanxi',
    '河南': 'Henan',
    '江苏': 'Jiangsu',
    '河北': 'Hebei',
    '辽宁': 'Liaoning',
    '广东': 'Guangdong',
    '内蒙古': 'Inner Mongolia',
    '贵州': 'Guizhou',
    '宁夏': 'Ningxia',
    '安徽': 'Anhui',
    '湖南': 'Hunan',
    '浙江': 'Zhejiang',
    '江西': 'Jiangxi',
    '新疆': 'Xinjiang',
    '海南': 'Hainan',
    '四川': 'Sichuan',
    '福建': 'Fujian',
    '山东': 'Shandong',
    '吉林': 'Jilin',
    '黑龙江': 'Heilongjiang',
    '广西': 'Guangxi',
    '上海': 'Shanghai',
    '天津': 'Tianjin',
    '重庆': 'Chongqing',
    '山西': 'Shanxi',
    '甘肃': 'Gansu',
    '北京': 'Beijing',
    '青海': 'Qinghai',
    '西藏': 'Tibet',
    'Wuhan': '武汉',
    'Xiaogan': '孝感',
    'Huanggang': '黄冈',
    'Jingzhou': '荆州',
    'Suizhou': '随州',
    'Xiangyang': '襄阳',
    'Ezhou': '鄂州',
    'Huangshi': '黄石',
    'Yichang': '宜昌',
    'Jingmen': '荆门',
    'Xianning': '咸宁',
    'Shiyan': '十堰',
    'peach of immortality': '仙桃',
    'Tianmen': '天门',
    'enshi': '恩施州',
    'Qianjiang': '潜江',
    'Shennongjia Forestry District ': '神农架林区',
    'Kunming': '昆明',
    'Zhaotong': '昭通',
    'Xishuangbanna': '西双版纳',
    'Qujing': '曲靖',
    'Yuxi': '玉溪',
    'Dali Prefecture': '大理州',
    'Baoshan': '保山',
    'Honghe Prefecture': '红河州',
    'Lijiang': '丽江',
    "Pu'er Tea": '普洱',
    'Dehong': '德宏州',
    'Chuxiong': '楚雄州',
    'Wenshan Prefecture': '文山州',
    'Lincang': '临沧',
    "Xi'an": '西安',
    'Hanzhoung': '汉中',
    'Ankang': '安康',
    'Weinan': '渭南',
    'Xianyang': '咸阳',
    'Baoji': '宝鸡',
    'Shangluo': '商洛',
    'Tongchuan': '铜川',
    "Yan'an": '延安',
    'Yulin': '玉林',
    'Hancheng': '韩城',
    'Yangling': '杨凌',
    'Areas to be defined': '待明确地区',
    'Xinyang': '信阳',
    'Nanyang': '南阳',
    'Zhumadian': '驻马店',
    'Zhengzhou': '郑州',
    'Shangqiu': '商丘',
    'Zhoukou': '周口',
    'Xinxiang': '新乡',
    'Pingdingshan': '平顶山',
    'Anyang': '安阳',
    'Xuchang': '许昌',
    'Luohe': '漯河',
    'Luoyang': '洛阳',
    'Jiaozuo': '焦作',
    'Kaifeng': '开封',
    'Hebi': '鹤壁',
    'Puyang': '濮阳',
    'Sanmenxia': '三门峡',
    'Jiyuan': '济源',
    'Suzhou': '宿州',
    'Nanjing': '南京',
    'Xuzhou': '徐州',
    'Huaian': '淮安',
    'Wuxi': '无锡',
    'Lianyungang': '连云港',
    'Changzhou': '常州',
    'Nantong': '南通',
    'Taizhou': '台州',
    'ynz': '盐城',
    'Yangzhou': '扬州',
    'Zhenjiang': '镇江',
    'Suqian': '宿迁',
    'Tangshan': '唐山',
    'Cangzhou': '沧州',
    'Zhangjiakou': '张家口',
    'Handan': '邯郸',
    'Shijiazhuang': '石家庄',
    'Baoding': '保定',
    'Langfang': '廊坊',
    'Xingtai': '邢台',
    'Qinghuangdao': '秦皇岛',
    'Chengde': '承德',
    'Hengshui': '衡水',
    'Shenyang': '沈阳',
    'Dalian': '大连',
    'Jinzhou': '锦州',
    'Panjin': '盘锦',
    'Huludao': '葫芦岛',
    'Fuxin': '阜新',
    'Tieling': '铁岭',
    'Chaoyang': '朝阳',
    'Dandong': '丹东',
    'Anshan': '鞍山',
    'Benxi': '本溪',
    'Liaoyang': '辽阳',
    'Yingkou': '营口',
    'Shenzhen': '深圳',
    'Guangzhou': '广州',
    'Dongguan': '东莞',
    'Zhuhai': '珠海',
    'Foshan': '佛山',
    'Zhongshan': '中山',
    'Huizhou': '惠州',
    'Jiangmen': '江门',
    'Shantou': '汕头',
    'Zhanjiang': '湛江',
    'Maoming': '茂名',
    'Zhaoqing': '肇庆',
    'Yangjiang': '阳江',
    'Meizhou': '梅州',
    'Qingyuan': '清远',
    'Shaoguan': '韶关',
    'Jieyang': '揭阳',
    'Chaozhou': '潮州',
    'Shanwei': '汕尾',
    'Heyuan': '河源',
    'Baotou': '包头',
    'Erdos': '鄂尔多斯',
    'Hohhot': '呼和浩特',
    'Tongliao': '通辽',
    'Bayannaoer': '巴彦淖尔',
    'Hulun Buir': '呼伦贝尔',
    'Chifeng': '赤峰',
    'Xilingol League': '锡林郭勒盟',
    'Wulanchabu': '乌兰察布',
    'Wuhai City': '乌海市',
    'Xingan Meng': '兴安盟',
    'Guiyang': '贵阳',
    'Zunyi': '遵义',
    'Bijie': '毕节',
    'Qiannan': '黔南州',
    'Qiandongnan Prefecture': '黔东南州',
    'Liupanshui': '六盘水',
    'Tongren': '铜仁',
    'Anshun': '安顺',
    'Qianxi': '黔西南州',
    'Yinchuan': '银川',
    'Wu Zhong': '吴忠',
    'Guyuan': '固原',
    'Central defender': '中卫',
    'Ningdong': '宁东',
    'Shizuishan': '石嘴山',
    'Bengbu': '蚌埠',
    'Hefei': '合肥',
    'Fuyang': '阜阳',
    'Bozhou': '亳州',
    "Lu'an": '六安',
    'Anqing': '安庆',
    "Ma'anshan": '马鞍山',
    'Wuhu': '芜湖',
    'Huaibei': '淮北',
    'Tongling': '铜陵',
    'Huainan': '淮南',
    'Chizhou': '池州',
    'Chuzhou': '滁州',
    'Mount Huangshan': '黄山',
    'Xuancheng': '宣城',
    'Changsha': '长沙',
    'Yueyang': '岳阳',
    'Shaoyang': '邵阳',
    'Zhuzhou': '株洲',
    'Changde': '常德',
    'Loudi': '娄底',
    'Yiyang': '益阳',
    'Chenzhou': '郴州',
    'Xiangtan': '湘潭',
    'city in Hunan': '衡阳',
    'Yongzhou': '永州',
    'Huaihua': '怀化',
    'Xiangxi Autonomous Prefecture': '湘西自治州',
    'Zhangjiajie': '张家界',
    'Wenzhou': '温州',
    'Ningbo': '宁波',
    'Hangzhou': '杭州',
    'Jiaxing': '嘉兴',
    'Jinhua': '金华',
    'Shaoxing': '绍兴',
    'Quzhou': '衢州',
    'Lishui': '丽水',
    'Huzhou': '湖州',
    'Zhoushan': '舟山',
    'Nanchang': '南昌',
    'Shangrao': '上饶',
    'Jiujiang': '九江',
    'Xinyu': '新余',
    'Yichun': '宜春',
    'Ganzhou': '赣州',
    'Fuzhou': '福州',
    'Pingxiang': '萍乡',
    'Yingtan': '鹰潭',
    "Ji'an": '吉安',
    'Jingdezhen': '景德镇',
    'Ganjiang New Area': '赣江新区',
    'Urumqi': '乌鲁木齐',
    'Yili Prefecture': '伊犁州',
    'The fourth division of the Corps': '兵团第四师',
    'The ninth division of the Corps': '兵团第九师',
    'changji': '昌吉州',
    'Bazhou': '巴州',
    'Shihezi City, the eighth division of the Corps': '兵团第八师石河子市',
    'Wujiaqu City, the sixth division of the Corps': '兵团第六师五家渠市',
    'The 12th division of the Corps': '兵团第十二师',
    'Turpan City': '吐鲁番市',
    '7th Division of corps': '兵团第七师',
    'Aksu Region': '阿克苏地区',
    'Sanya': '三亚',
    'Haikou': '海口',
    'Danzhou': '儋州',
    'Wanning': '万宁',
    'Changjiang': '昌江',
    'Chengmai': '澄迈',
    'Qionghai': '琼海',
    'ascend a height': '临高',
    'Lingshui': '陵水',
    'Baoting': '保亭',
    'east': '东方',
    'God of Literature': '文昌',
    'Ledong': '乐东',
    'Ding An': '定安',
    'Qiong Zhong': '琼中',
    'Chengdu': '成都',
    'The state of Gansu': '甘孜州',
    'Dazhou': '达州',
    'Nao': '南充',
    "Guang'an": '广安',
    'Bazhong': '巴中',
    'Neijiang': '内江',
    'Mianyang': '绵阳',
    'Luzhou': '泸州',
    'Deyang': '德阳',
    'Yibin': '宜宾',
    'Liangshan Prefecture': '凉山州',
    'Zigong': '自贡',
    'Suining': '遂宁',
    'Meishan': '眉山',
    "Ya'an": '雅安',
    'Guangyuan': '广元',
    'Panzhihua': '攀枝花',
    'Leshan': '乐山',
    'Ziyang': '资阳',
    'Aba Prefecture': '阿坝州',
    'Putian': '莆田',
    'Quanzhou': '泉州',
    'Xiamen': '厦门',
    'Ningde': '宁德',
    'Nanping': '南平',
    'Zhangzhou': '漳州',
    'Sanming': '三明',
    'Longyan': '龙岩',
    'Qingdao': '青岛',
    "Ji'nan": '济南',
    'Yantai': '烟台',
    'Weifang': '潍坊',
    'Liaocheng': '聊城',
    'Linyi': '临沂',
    'Jining': '济宁',
    'Weihai': '威海',
    'Dezhou': '德州',
    "Tai'an": '泰安',
    'Zibo': '淄博',
    'Zaozhuang': '枣庄',
    'sunshine': '日照',
    'Heze': '菏泽',
    'Binzhou': '滨州',
    'Changchun': '长春',
    'Siping City': '四平市',
    'Liaoyuan': '辽源',
    'Gongzhuling': '公主岭',
    'Yanbian': '延边',
    'make well-connected': '通化',
    'Jilin City': '吉林市',
    'Songyuan': '松原',
    'Baicheng': '白城',
    'Meihekou': '梅河口',
    'Harbin': '哈尔滨',
    'Shuangyashan': '双鸭山',
    'Jixi': '鸡西',
    'Suihua': '绥化',
    'Qiqihar': '齐齐哈尔',
    'Daqing': '大庆',
    'Qitaihe': '七台河',
    'Heihe': '黑河',
    'Mudanjiang': '牡丹江',
    'Jiamusi': '佳木斯',
    'Hegang': '鹤岗',
    'Greater Khingan Range': '大兴安岭',
    'Nanning': '南宁',
    'The North Sea': '北海',
    'Guilin': '桂林',
    'Hechi': '河池',
    'Port of Fangcheng': '防城港',
    'city in Guangxi': '柳州',
    'Guest': '来宾',
    'Qinzhou': '钦州',
    'Guigang': '贵港',
    'Hezhou': '贺州',
    'Baise': '百色',
    'Wuzhou': '梧州',
    'Foreign visitors to Shanghai': '外地来沪人员',
    'Pudong New Area': '浦东新区',
    'Baoshan District': '宝山区',
    'Xuhui District': '徐汇区',
    'Minhang District': '闵行区',
    'Jingan District': '静安区',
    'Songjiang District': '松江区',
    'Putuo District': '普陀区',
    'Changning District': '长宁区',
    'Yangpu District': '杨浦区',
    'Jiading District': '嘉定区',
    'Fengxian District': '奉贤区',
    'Hongkou District': '虹口区',
    'Huangpu District': '黄浦区',
    'Qingpu District': '青浦区',
    'Chongming District': '崇明区',
    'Jinshan District': '金山区',
    'Baodi District': '宝坻区',
    'Hedong District': '河东区',
    'Hebei District': '河北区',
    'Beichen District': '北辰区',
    'Nankai District': '南开区',
    'Heping District': '和平区',
    'Personnel from other places coming to Tianjin': '外地来津人员',
    'Ninghe District': '宁河区',
    'Dongli District': '东丽区',
    'Hexi District': '河西区',
    'Binhai New Area': '滨海新区',
    'Xiqing District': '西青区',
    'Hongqiao District': '红桥区',
    'Jinnan District': '津南区',
    'Wuqing District': '武清区',
    'Wanzhou District': '万州区',
    'Jiangbei District': '江北区',
    'Qijiang District': '綦江区',
    'Hechuan District': '合川区',
    'Dianjiang County': '垫江县',
    'Fengjie County': '奉节县',
    'Yuzhong District': '渝中区',
    'jiulongpo district': '九龙坡区',
    'Tongnan District': '潼南区',
    "Nan'an District": '南岸区',
    'Liangjiang New Area': '两江新区',
    'Dazu District': '大足区',
    'Zhongxian': '忠县',
    'Yubei District': '渝北区',
    'Shizhu County': '石柱县',
    'Yunyang County': '云阳县',
    'Longevity district': '长寿区',
    'Fengdu County': '丰都县',
    'Rongchang District': '荣昌区',
    'shapingba district': '沙坪坝区',
    'Kai Zhou District': '开州区',
    'Tongliang District': '铜梁区',
    'Wuxi County': '巫溪县',
    'Wushan County': '巫山县',
    'Bishan District': '璧山区',
    'Banan District': '巴南区',
    'Yongchuan District': '永川区',
    'dadukou district': '大渡口区',
    'Jiangjin District': '江津区',
    'High-tech Zone': '高新区',
    'Liangping District': '梁平区',
    'Fuling District': '涪陵区',
    'Pengshui County': '彭水县',
    'Wulong District': '武隆区',
    'Youyang County': '酉阳县',
    'Wansheng Economic Development Zone': '万盛经开区',
    'Chengkou County': '城口县',
    'Qianjiang District': '黔江区',
    'Xiushan County': '秀山县',
    'Jinzhong': '晋中',
    'Taiyuan': '太原',
    'Yuncheng': '运城',
    'Da Tong': '大同',
    'CiH': '长治',
    'Xinzhou': '忻州',
    'Jincheng': '晋城',
    'Shuozhou': '朔州',
    'Yangquan': '阳泉',
    'Lvliang': '吕梁',
    'Linfen': '临汾',
    'Lanzhou': '兰州',
    'Pingliang': '平凉',
    'Gannan': '甘南',
    'Tianshui': '天水',
    'Dingxi': '定西',
    'silver': '白银',
    'Longnan': '陇南',
    'Qingyang': '庆阳',
    'Linxia': '临夏',
    'Zhangye': '张掖',
    'Jinchang': '金昌',
    'Chaoyang District': '朝阳区',
    'Pinggu District':'平谷区',
    'Haidian District': '海淀区',
    'Xicheng District': '西城区',
    'Daxing District': '大兴区',
    'Fengtai District': '丰台区',
    'Foreign visitors to Beijing': '外地来京人员',
    'Changping District': '昌平区',
    'Tongzhou District': '通州区',
    'Fangshan District': '房山区',
    'Shijingshan District': '石景山区',
    'Dongcheng District': '东城区',
    'Shunyi District': '顺义区',
    'Huairou District': '怀柔区',
    'Miyun District': '密云区',
    'Mentougou District': '门头沟区',
    'Yanqing District': '延庆区',
    'Xining': '西宁',
    'Haibei Prefecture': '海北州',
    'Lhasa': '拉萨',
    'Hubei': '湖北',
    'Yunnan': '云南',
    'Shaanxi': '陕西',
    'Henan': '河南',
    'Jiangsu': '江苏',
    'Hebei': '河北',
    'Liaoning': '辽宁',
    'Taiwan': '台湾',
    'Guangdong': '广东',
    'Inner Mongolia': '内蒙古',
    'Guizhou': '贵州',
    'Ningxia': '宁夏',
    'Anhui': '安徽',
    'Hunan': '湖南',
    'Zhejiang': '浙江',
    'Jiangxi': '江西',
    'Xinjiang': '新疆',
    'Hainan': '海南',
    'Sichuan': '四川',
    'Fujian': '福建',
    'Shandong': '山东',
    'Jilin': '吉林',
    'Heilongjiang': '黑龙江',
    'Guangxi': '广西',
    'Shanghai': '上海',
    'Tianjin': '天津',
    'Chongqing': '重庆',
    'Shanxi': '山西',
    'Gansu': '甘肃',
    'Beijing': '北京',
    'Qinghai': '青海',
    'Tibet': '西藏',
    'Tokyo': '东京都', 'Kanagawa': '神奈川', 'Hokkaido': '北海道', 'Wakayama': '和歌山', 'Chiba': '千叶', 'Kumamoto': '熊本', 'Ishikawa': '石川', 'Okinawa': '冲绳', 'Fukuoka': '福冈', 'Mie': '三重', 'Saitama': '埼玉', 'Aichi': '爱知', 'Osaka': '大阪府', 'Kyoto': '京都府', 'Nagano': '长野', 'Gifu': '岐阜', 'Kochi': '高知', 'Niigata': '新泻', 'Ehime': '爱媛', 'Tochigi': '栃木', 'Tokushima': '德岛', 'Miyagi': '宫城', 'Shizuoka': '静冈', 'Hyogo': '兵库', 'Nara': '奈良', 'Cruise': '邮轮', 'Related personnel for quarantine, quarantine and handling': '检疫、隔离及搬运等相关人员', 'Chartered': '包机', 'Oita': '大分县', 'Yamaguchi': '山口', 'Shiga': '滋贺', 'Miyazaki': '宫崎', 'Akita': '秋田', 'Yamanashi': '山梨', 'Hiroshima': '广岛', 'Gunma': '群马', 'Fukushima': '福岛',
    'North Gyeongsang': '庆尚北道', 'Busan': '釜山', 'Gyeonggi': '京畿道', 'Seoul': '首尔', 'Daejeon': '大田', 'Ulsan': '蔚山', 'South Gyeongsang': '庆尚南道', 'Gwangju': '光州市', 'Daegu': '大邱', 'South Chungcheong': '忠清南道', 'Gangwon': '江原道', 'North Chungcheong': '忠清北道', 'Incheon': '仁川', 'North Jeolla': '全罗北道', 'South Jeolla': '全罗南道', 'Sejong': '世宗', 'Jeju': '济州岛',
    'Trentino-Alto Adige': '特伦蒂诺-上阿迪杰', 'Lombardy': '伦巴第', 'Emilia-Romagna': '艾米利亚-罗马涅', 'Veneto': '威尼托', 'Piemont': '皮埃蒙特', 'Marche': '马尔凯', 'Liguria': '利古里亚', 'Campania': '坎帕尼亚', 'Tuscany': '托斯卡纳', 'Friuli Venezia Giulia': '弗留利-威尼斯朱利亚', 'Lazio': '拉齐奥', 'Sicily': '西西里', 'Abruzzo': '阿布鲁佐', 'Apulia': '普利亚', 'Umbria': '翁布里亚', 'Calabria': '卡拉布里亚', 'Bolzano': '博尔扎诺', 'To be confirmed': '待确认', 'Trento': '特伦托', 'Molise': '莫利塞', 'Sardinia': '撒丁岛', 'Basilicata': '巴西利卡塔','Aosta Valley': '瓦莱达奥斯塔',
    'Alabama': '阿拉巴马州',
    'Alaska': '阿拉斯加',
    'Arizona': '亚利桑那州',
    'Arkansas': '阿肯色州',
    'California': '加利福尼亚州',
    'Colorado': '科罗拉多州',
    'Connecticut': '康涅狄格州',
    'Delaware': '特拉华州',
    'Florida': '佛罗里达州',
    'Georgia': '乔治亚州',
    'Hawaii': '夏威夷州',
    'Idaho': '爱达荷州',
    'Illinois': '伊利诺伊州',
    'Indiana': '印第安纳州',
    'Iowa': '爱荷华州',
    'Kansas': '堪萨斯州',
    'Kentucky': '肯塔基州',
    'Louisiana': '路易斯安那州',
    'Maine': '缅因州',
    'Maryland': '马里兰州',
    'Massachusetts': '马萨诸塞州',
    'Michigan': '密歇根州',
    'Minnesota': '明尼苏达州',
    'Mississippi': '密西西比州',
    'Missouri': '密苏里州',
    'Montana': '蒙大拿州',
    'Nebraska': '内布拉斯加州',
    'Nevada': '内华达州',
    'New Hampshire': '新罕布什尔州',
    'New Jersey': '新泽西州',
    'New Mexico': '新墨西哥州',
    'New York': '纽约州',
    'North Carolina': '北卡罗来纳州',
    'North Dakota': '北达科他州',
    'Ohio': '俄亥俄州',
    'Oklahoma': '俄克拉荷马州',
    'Oregon': '俄勒冈州',
    'Pennsylvania': '宾夕法尼亚州',
    'Rhode Island': '罗德岛',
    'South Carolina': '南卡罗来纳州',
    'South Dakota': '南达科他州',
    'Tennessee': '田纳西州',
    'Texas': '德克萨斯州',
    'Utah': '犹他州',
    'Vermont': '佛蒙特州',
    'Virginia': '弗吉尼亚州',
    'Washington': '华盛顿州',
    'West Virginia': '西弗吉尼亚州',
    'Wisconsin': '威斯康星州',
    'Wyoming': '怀俄明州',
    'District of Columbia': '哥伦比亚特区',
    'Unassigned Location (From Diamond Princess)': '未指定位置（来自钻石公主）',
    'Grand Princess Cruise Ship': '大公主邮轮',
    'Alberta': '艾伯塔省',
    'British Columbia': '不列颠哥伦比亚省',
    'Manitoba': '马尼托巴',
    'New Brunswick': '新不伦瑞克',
    'Newfoundland and Labrador': '纽芬兰和拉布拉多',
    'Nova Scotia': '新斯科舍',
    'Northwest Territories': '西北地区',
    'Nunavut': '努纳武特',
    'Ontario': '安大略省',
    'Prince Edward Island': '爱德华王子岛',
    'Quebec': '魁北克',
    'Saskatchewan': '萨斯喀彻温省',
    'Yukon': '育空',
    'New South Wales': '新南威尔士',
    'Queensland': '昆士兰',
    'South Australia': '南澳大利亚',
    'Tasmania':'塔斯马尼亚',
    'Victoria':'维多利亚',
    'Western Australia':'西澳大利亚',
    'Australian Capital Territory': '首都领地',
    'Northern Territory': '北领地',
    'From Diamond Princess': '钻石公主号'
};